/**
 * This file was generated by the Jeddict
 */
package entity;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * @author 17682
 */
@Entity
public class Commento {

    @Id
    @GeneratedValue(generator = "A", strategy = GenerationType.SEQUENCE)
    @SequenceGenerator(name = "A")
    private Long id;

    @Basic
    @Temporal(TemporalType.DATE)
    private Date DataOra;

    @Basic
    private String Testo;

    @Basic
    private String Titolo;

    @ManyToOne(targetEntity = Utente.class)
    private Utente utente;

    @ManyToOne(targetEntity = Post.class)
    private Post post;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getDataOra() {
        return this.DataOra;
    }

    public void setDataOra(Date DataOra) {
        this.DataOra = DataOra;
    }

    public String getTesto() {
        return this.Testo;
    }

    public void setTesto(String Testo) {
        this.Testo = Testo;
    }

    public String getTitolo() {
        return this.Titolo;
    }

    public void setTitolo(String Titolo) {
        this.Titolo = Titolo;
    }

    public Utente getUtente() {
        return this.utente;
    }

    public void setUtente(Utente utente) {
        this.utente = utente;
    }

    public Post getPost() {
        return this.post;
    }

    public void setPost(Post post) {
        this.post = post;
    }

}