/**
 * This file was generated by the Jeddict
 */
package entity;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;

/**
 * @author 17682
 */
@Entity
public class Utente {

    @Id
    @GeneratedValue(generator = "A", strategy = GenerationType.SEQUENCE)
    @SequenceGenerator(name = "A")
    private Long id;

    @Column(unique = true, nullable = false)
    @Basic
    private String Username;

    @Column(unique = true, nullable = false)
    @Basic
    private String Email;

    @Column(nullable = false)
    @Basic
    private String Password;

    @Column(nullable = false)
    @Basic
    private String SALT;

    @Column(nullable = false)
    @Basic
    private String Livello;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return this.Username;
    }

    public void setUsername(String Username) {
        this.Username = Username;
    }

    public String getEmail() {
        return this.Email;
    }

    public void setEmail(String Email) {
        this.Email = Email;
    }

    public String getPassword() {
        return this.Password;
    }

    public void setPassword(String Password) {
        this.Password = Password;
    }

    public String getSALT() {
        return this.SALT;
    }

    public void setSALT(String SALT) {
        this.SALT = SALT;
    }

    public String getLivello() {
        return this.Livello;
    }

    public void setLivello(String Livello) {
        this.Livello = Livello;
    }

}